/*

try
{
     do some stuff with bureaucrats
}
catch (std::exception & e)
{
    handle exception
}
*/